# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/ArchSoftware/afoil-engine
    username: arch-dev
    password: ${{ secrets.PKG_ACCESS_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ops"

  - package-ecosystem: "gradle"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
    groups:
      kotlin-ksp:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "com.google.devtools.ksp"
    commit-message:
      prefix: "build"
