name: Build

on:
    push:
        branches:
            - main

jobs:
    build_apk:
        name: "Build APK"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                  gradle-home-cache-cleanup: true

            - name: Check build-logic
              run: ./gradlew check -p build-logic

            - name: Build APK
              run: ./gradlew assembleDebug

            - name: Upload APKs
              uses: actions/upload-artifact@v4
              with:
                  name: APKs
                  path: '**/build/outputs/apk/**/*.apk'