name: Build

on:
    push:
        branches:
            - main

jobs:
    check_commits_types:
        name: Check commit types
        runs-on: ubuntu-latest
        outputs:
          contain_docs: ${{ steps.check.outputs.contain_docs }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Check commit types
            id: check
            run: |
              contain_docs=true
              for commit in "${{ github.event.commits }}"; do
                if [[ "$commit.message" != "docs:"* ]]; then
                  contain_docs=false
                  break
                fi
              done
              echo "contain_docs=$contain_docs" >> $GITHUB_OUTPUT

    build_apk:
        name: Build APK
        runs-on: ubuntu-latest
        needs: check_commits_types
        if: ${{ needs.check_commits_types.outputs.contain_docs == 'false' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                  gradle-home-cache-cleanup: true

            - name: Check build-logic
              run: ./gradlew check -p build-logic

            - name: Create and push new module graphs
              run: |
                ./gradlew createModuleGraph
                if ! git diff-index --quiet --ignore-submodules --ignore-cr-at-eol HEAD --; then
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git add \*.md
                  git commit -m 'docs: update module graphs'
                fi

            - name: Build APK
              run: ./gradlew assembleDebug
              env:
                GITHUB_USERNAME: arch-dev
                GITHUB_TOKEN: ${{ secrets.PKG_ACCESS_TOKEN }}

            - name: Upload APKs
              uses: actions/upload-artifact@v4
              with:
                  name: APKs
                  path: '**/build/outputs/apk/**/*.apk'