name: Build

on:
    push:
        branches:
            - main

jobs:
    build_apk:
        name: "Build APK"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                  gradle-home-cache-cleanup: true

            - name: Check build-logic
              run: ./gradlew check -p build-logic

            - name: Create and push new module graphs
              run: |
                ./gradlew createModuleGraph
                if ! git diff-index --quiet --ignore-submodules --ignore-cr-at-eol HEAD --; then
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git add \*.md
                  git commit -m 'docs: update module graphs'
                fi

            - name: Build APK
              run: ./gradlew assembleDebug
              env:
                GITHUB_USERNAME: arch-dev
                GITHUB_TOKEN: ${{ secrets.PKG_ACCESS_TOKEN }}

            - name: Upload APKs
              uses: actions/upload-artifact@v4
              with:
                  name: APKs
                  path: '**/build/outputs/apk/**/*.apk'